### ISSUE TITLE
Meson could not be found after installing

### ISSUE THREAD

**Issue by hughsie** [BSFishy/meson-build#2]
Maybe I'm doing this wrong, but I couldn't get the action working at all:

    Successfully built meson
    Installing collected packages: meson
    Successfully installed meson-0.52.1
    ##[error]Meson could not be found after installing

This is with https://github.com/hughsie/libjcat/runs/549943632

Many thanks.

**Comment by BSFishy** [comment]
Looking at your workflow, I notice two things. The first is that you are installing Python through apt, rather than using the [`setup-python` action](https://github.com/actions/setup-python). That action will setup Python correctly, from a cache that is already on the machine so it is not only faster, but is reproducible. I have a feeling that the issue resides in Python not being correctly setup due to it using apt. Is there any reason that you were using apt rather than the action?

I also notice that you were installing Ninja through apt. Although you can do that, this action will actually install it through pip if it is not already installed. If you need the latest version through apt, that is fine, but using the action to install it makes your workflow look a little cleaner. Just a tip ;)

**Comment by hughsie** [comment]
Yes, using setup-python action makes it work. Thank you for explaining this to me, and sorry for the noise!
